
export const PARTS_WITHOUT_QUESTION_GROUP = [1,2,3,4,5]

export const PARTS_WITHOUT_ANSWER_CONTENT = [1,2]

export const PART_NEED_QUESTION_GROUP_INDEX = [6]

export const PART_NEED_QUESTION_INDEX = [1,2,3,4,6]